baseURL = 'https://danielparrish.me/'
languageCode = 'en-us'
title = 'Daniel Parrish'
theme = "gokarna"

# Directory that compiled site is published in when running 'hugo' command
publishDir = "public"

# Automatically generate robots.txt
enableRobotsTXT = true

# Code highlighting theme
pygmentsStyle = "monokai"

# Make post list page titles not plural
# (fix the Musics issue)
pluralizelisttitles = false

# Enable emoji shorthand in content files
enableEmoji = true

# Enable auto-rewrite of relative URLs to be relative to current content
relativeURLs = false

[params]
    # Copyright text
    footer = "Daniel Parrish"

    # Link highlight color
    # DEEEPIII GREEN accentColor = "#19a357"
    accentColor = "#ffa8ff"

    # Main avatar image
    avatarURL = "/images/picrew7065.png"

    # Homepage site description
    description = "I may not know exactly where I'm going, but I know I'm on the right track"

[menu]

    [[menu.main]]
        identifier = "music"
        name = "Music"
        url = "/music/"
        weight = 1

    #[[menu.main]]
    #    identifier = "art"
    #    name = "Art"
    #    url = "/art/"
    #    weight = 2 

    #[[menu.main]]
    #    identifier = "code"
    #    name = "Code"
    #    url = "/code/"
    #    weight = 3   

    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 4               

    # Tags Header Link
    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 5

    # Youtube Header Link  
    [[menu.main]]
        identifier = "youtube"
        url = "https://www.youtube.com/channel/UCyYkOrULZdGwLszf2UK5n-A"
        weight = 6
        # for icon: https://feathericons.com/
        pre = "<span data-feather='youtube'></span>"

